### ISSUE TITLE
UnboundLocalError: local variable 'scene_info' referenced before assignment

### ISSUE THREAD

**Issue by chojaework** [BaowenZ/RaDe-GS#55]
Hi, I get this error when I try to run this command.

`
python train.py -s <path to DTU dataset> -m <output folder> -r 2 --use_decoupled_appearance
`

Detailed error logs is given as below.

`
parser:  ArgumentParser(prog='train.py', usage=None, description='Training script parameters', formatter_class=<class 'argparse.HelpFormatter'>, conflict_handler='error', add_help=True)
Optimizing /RaDe-GS/outputs
Output folder: /RaDe-GS/outputs [24/09 16:26:05]
Tensorboard not available: not logging progress [24/09 16:26:05]
Traceback (most recent call last):
  File "/RaDe-GS/train.py", line 306, in <module>
    training(dataset=lp.extract(args),
  File "/RaDe-GS/train.py", line 65, in training
    scene = Scene(dataset, gaussians)
  File "/RaDe-GS/scene/__init__.py", line 50, in __init__
    with open(scene_info.ply_path, 'rb') as src_file, open(os.path.join(self.model_path, "input.ply") , 'wb') as dest_file:
UnboundLocalError: local variable 'scene_info' referenced before assignment
`

Can I get some help solving this issue please?? Thank you in advance! :)

**Comment by chojaework** [comment]
Solved by setting the right path to the training dataset.
