### ISSUE TITLE
CUDA error: an illegal memory access was encountered

### ISSUE THREAD

**Issue by LiuShuai086** [BaowenZ/RaDe-GS#63]
按照源码进行训练不会出现CUDA error，但是我在create_from_pcd的时候初始化2d gaussian，scale[:, 2] -= 1e10，训练刚开始会出现以下报错：
Traceback (most recent call last):
  File "/mnt/sda/2_lius/RaDe-GS/train.py", line 306, in <module>
    training(dataset=lp.extract(args),
  File "/mnt/sda/2_lius/RaDe-GS/train.py", line 126, in training
    render_pkg = render(viewpoint_cam, gaussians, pipe, background, kernel_size, require_coord = require_coord and reg_kick_on, require_depth = require_depth and reg_kick_on)
  File "/mnt/sda/2_lius/RaDe-GS/gaussian_renderer/__init__.py", line 81, in render
    print("Any NaNs in radii:", torch.isnan(radii).any())
  File "/home/ubuntu/miniconda3/envs/radegs_lius/lib/python3.9/site-packages/torch/_tensor.py", line 463, in __repr__
    return torch._tensor_str._str(self, tensor_contents=tensor_contents)
  File "/home/ubuntu/miniconda3/envs/radegs_lius/lib/python3.9/site-packages/torch/_tensor_str.py", line 698, in _str
    return _str_intern(self, tensor_contents=tensor_contents)
  File "/home/ubuntu/miniconda3/envs/radegs_lius/lib/python3.9/site-packages/torch/_tensor_str.py", line 618, in _str_intern
    tensor_str = _tensor_str(self, indent)
  File "/home/ubuntu/miniconda3/envs/radegs_lius/lib/python3.9/site-packages/torch/_tensor_str.py", line 350, in _tensor_str
    formatter = _Formatter(get_summarized_data(self) if summarize else self)
  File "/home/ubuntu/miniconda3/envs/radegs_lius/lib/python3.9/site-packages/torch/_tensor_str.py", line 134, in __init__
    value_str = f"{value}"
  File "/home/ubuntu/miniconda3/envs/radegs_lius/lib/python3.9/site-packages/torch/_tensor.py", line 986, in __format__
    return self.item().__format__(format_spec)
RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
请问能给我一些建议吗？

**Comment by xxxrc4** [comment]
radegs不能初始化为2dgs，因为forward.cu里面的computeCov2D函数中会对3d协方差矩阵特征分解，当有一个scale特别小的时候，bool well_conditioned = Vrk_eigen_value[min_id]>0.00000001会是false，此时会出错。所以如果你要初始化为2dgs,你就需要自己修改cuda代码了。
